# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RNMeteorStarter.xcodeproj")
    build_app(workspace: "RNMeteorStarter.xcworkspace", scheme: "RNMeteorStarter")
    upload_to_testflight
  end
end

platform :ios do
  desc "Push a new build to AppStore"
    lane :release do
    increment_build_number(xcodeproj: "RNMeteorStarter.xcodeproj")
      #capture_screenshots                  # generate new screenshots for the App Store
      sync_code_signing(type: "appstore")  # see code signing guide for more information
      build_app(workspace: "RNMeteorStarter.xcworkspace", scheme: "RNMeteorStarter")
      upload_to_app_store                  # upload your app to iTunes Connect
    end
end
